# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ms-enterprise-customer

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://everisbank.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e2541b1a8d8f49c2b87776e0d0106a87 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4780160cc3b04672a9df950ee3c7868a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e2541b1a8d8f49c2b87776e0d0106a87 }}/ms-enterprise-customer:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ms-enterprise-customer'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f8436d714b3f4e96be7773ff292db349 }}
        images: 'everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e2541b1a8d8f49c2b87776e0d0106a87 }}/ms-enterprise-customer:${{ github.sha }}'